# Generated by Django 4.1.2 on 2022-12-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
