# Generated by Django 4.1.2 on 2022-12-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
