# Generated by Django 4.1.2 on 2022-12-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
    ]
